services:
  db:
    image: docker.io/library/postgres:18.0-alpine3.22@sha256:48c8ad3a7284b82be4482a52076d47d879fd6fb084a1cbfccbd551f9331b0e40
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: solaceassignment
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  psql:
